# SPDX-License-Identifier: Apache-2.0
#
# Regenerates the .sav / .zsav fixtures in this directory.
#
#   python3 -m venv venv && venv/bin/pip install pyreadstat
#   venv/bin/python make_fixtures.py
#
# Most fixtures are written with pyreadstat (a wrapper over ReadStat, the
# reference reader/writer used by R haven and Python). Two are hand-crafted
# byte by byte because ReadStat cannot write them: a legacy codepage-1252
# file with no character-encoding record, and a multi-block .zsav. Both are
# read back with pyreadstat after writing, so every fixture in this
# directory is confirmed readable by the reference implementation.
#
# All fixtures are synthetic and generated by this script; no third-party or
# customer data. Reruns are byte-identical except for the creation date/time
# ReadStat stamps into the 176-byte header.

import struct
import zlib
from pathlib import Path

import pandas as pd
import pyreadstat

HERE = Path(__file__).parent


def write(name, df, **kw):
    path = HERE / name
    pyreadstat.write_sav(df, str(path), **kw)
    back, meta = pyreadstat.read_sav(str(path), user_missing=True)
    assert len(back) == len(df), name
    print(f"{name}: {len(back)} rows x {len(back.columns)} cols, "
          f"{path.stat().st_size} bytes, compression={header_compression(path)}")
    return back, meta


def header_compression(path):
    with open(path, "rb") as f:
        h = f.read(80)
    return struct.unpack("<i", h[72:76])[0]


# --- types: every column shape, in all three compression modes -------------------
#
# Numeric values chosen for bytecode coverage: integers in [-99, 151] compress
# to a single command byte (code = value + bias, bias 100); anything else is a
# 253-literal; None is system-missing (255); an all-spaces string is 254.

types_df = pd.DataFrame({
    "id": [1.0, 2.0, 3.0, 4.0],                       # command-byte integers
    "score": [-99.0, 151.0, 0.5, None],               # bias edges, literal, sysmis
    "big": [1e300, -2.75, 9007199254740992.0, 0.0],   # 253-literals
    "str8": ["", "abc", "héllo ✓", "x"],              # single-element string
    "str20": ["", "twenty char string!!", "short", "padded      end"],
})

write("types.sav", types_df)                          # compression 0
write("rowcomp.sav", types_df, row_compress=True)     # compression 1 (bytecode)
write("types.zsav", types_df, compress=True)          # compression 2 (zlib)

# --- labels: dictionary metadata is the differentiator ---------------------------

labels_df = pd.DataFrame({
    "gender": [1.0, 2.0, 1.0, 9.0],
    "rating": [1.0, 5.0, -97.0, 3.0],
    "vote": ["Y", "N", "", "Y"],
    "comment_text_very_long_name": ["fine", "bad", "", "ok"],
})

write(
    "labels.sav", labels_df, row_compress=True,
    file_label="driverless label fixture",
    column_labels={
        "gender": "Respondent gender",
        "rating": "Satisfaction rating",
        "vote": "Voted yes/no",
        "comment_text_very_long_name": "Free-text comment",
    },
    variable_value_labels={
        "gender": {1.0: "Male", 2.0: "Female", 9.0: "No answer"},
        "rating": {1.0: "Awful", 5.0: "Great"},
        "vote": {"Y": "Yes", "N": "No"},
    },
    missing_ranges={
        "gender": [9.0],
        "rating": [{"lo": -99.0, "hi": -90.0}],
    },
    variable_measure={
        "gender": "nominal", "rating": "ordinal",
        "vote": "nominal", "comment_text_very_long_name": "nominal",
    },
    variable_display_width={"gender": 6, "rating": 10},
)

# --- dates: SPSS epoch is 1582-10-14, seconds ------------------------------------

dates_df = pd.DataFrame({
    "d": pd.to_datetime(["2026-07-15", "1969-12-31", "1582-10-15", None]).date,
    "dt": pd.to_datetime(["2026-07-15 13:45:30", "1900-01-01 00:00:01",
                          "2000-02-29 23:59:59", None]),
    "t": [pd.Timestamp("1900-01-01 13:45:30").time(),
          pd.Timestamp("1900-01-01 00:00:00").time(),
          pd.Timestamp("1900-01-01 23:59:59").time(), None],
})

write("dates.sav", dates_df, row_compress=True,
      variable_format={"d": "DATE11", "dt": "DATETIME20", "t": "TIME8"})

# --- longstr: very long strings (>255) and long variable names -------------------
#
# A width-300 string is 2 segments (255 + 48), width 600 is 3 (255+255+96),
# width 256 is the 2-segment edge, width 255 the single-segment maximum.

longstr_df = pd.DataFrame({
    "long_name_for_a_string_variable": ["A" * 300, "b" * 10, ""],
    "exactly255": ["C" * 255, "", "d" * 254],
    "exactly256": ["E" * 256, "f" * 256, ""],
    "sixhundred": ["G" * 600, "", "h" * 300],
    "tail": [1.0, 2.0, 3.0],
})

write("longstr.sav", longstr_df, row_compress=True)

# --- empty: dictionary only, zero cases ------------------------------------------

empty_df = pd.DataFrame({"a": pd.Series(dtype="float64"),
                         "b": pd.Series(dtype="object")})
write("empty.sav", empty_df, row_compress=True)


# =================================================================================
# Hand-crafted fixtures. ReadStat always writes UTF-8 with an encoding record
# and single-block zsav, so these two are built byte by byte and then verified
# by reading them back with pyreadstat.
# =================================================================================

SYSMIS = struct.unpack("<d", struct.pack("<Q", 0xFFEFFFFFFFFFFFFF))[0]  # -DBL_MAX


def fmt(ftype, width, dec=0):
    return (ftype << 16) | (width << 8) | dec


def var_record(vtype, name, print_fmt, write_fmt, label=None, missing=None):
    out = struct.pack("<iiiiii", 2, vtype, 1 if label else 0,
                      len(missing) if missing else 0, print_fmt, write_fmt)
    out += name.ljust(8)[:8].encode("ascii")
    if label:
        lb = label
        out += struct.pack("<i", len(lb)) + lb
        out += b"\x00" * ((4 - len(lb) % 4) % 4)
    if missing:
        for m in missing:
            out += struct.pack("<d", m)
    return out


def continuation():
    return struct.pack("<iiiiii", 2, -1, 0, 0, 0, 0) + b" " * 8


def info_record(subtype, size, payload):
    assert len(payload) % size == 0
    return struct.pack("<iiii", 7, subtype, size, len(payload) // size) + payload


def header(compression, case_size, ncases, label=b"", bias=100.0):
    return (b"$FL2"
            + b"@(#) SPSS DATA FILE driverless test writer".ljust(60)
            + struct.pack("<iiiii", 2, case_size, compression, 0, ncases)
            + struct.pack("<d", bias)
            + b"01 Jan 26" + b"00:00:00"
            + label.ljust(64)[:64]
            + b"\x00" * 3)


def machine_records(charcode):
    ints = struct.pack("<8i", 1, 0, 0, 1, 1, 1, 2, charcode)
    flts = struct.pack("<3d", SYSMIS, struct.unpack("<d", struct.pack("<Q", 0x7FEFFFFFFFFFFFFF))[0], SYSMIS)
    return info_record(3, 4, ints) + info_record(4, 8, flts)


# --- legacy1252.sav: codepage 1252 strings, no subtype-20 encoding record --------
# The shape of a pre-Unicode SPSS file: charcode 1252 in the machine integer
# record is the only encoding hint. Uncompressed data.

enc = lambda s, w: s.encode("cp1252").ljust(w)

city_w = 16   # two 8-byte elements
rows = [
    (1.0, "Málaga"),
    (2.0, "Zürich"),
    (3.0, "León"),
    (SYSMIS, ""),
]

body = header(0, 1 + city_w // 8, len(rows), b"legacy cp1252 fixture")
body += var_record(0, "NUM", fmt(5, 8, 2), fmt(5, 8, 2), label="Numéro".encode("cp1252"))
body += var_record(city_w, "CITY", fmt(1, city_w), fmt(1, city_w))
body += continuation()
# value labels for NUM: rec 3 (labels) + rec 4 (variable index)
labels = [(1.0, "première".encode("cp1252")), (2.0, "deuxième".encode("cp1252"))]
rec3 = struct.pack("<ii", 3, len(labels))
for v, lb in labels:
    lb = lb[:255]
    pad = (8 - (1 + len(lb)) % 8) % 8
    rec3 += struct.pack("<d", v) + bytes([len(lb)]) + lb + b" " * pad
rec4 = struct.pack("<iii", 4, 1, 1)
body += rec3 + rec4
body += machine_records(1252)
body += struct.pack("<ii", 999, 0)
for num, city in rows:
    body += struct.pack("<d", num) + enc(city, city_w)

path = HERE / "legacy1252.sav"
path.write_bytes(body)
back, meta = pyreadstat.read_sav(str(path))
assert list(back["CITY"]) == ["Málaga", "Zürich", "León", ""], list(back["CITY"])
assert meta.value_labels, "value labels lost"
print(f"legacy1252.sav: {len(back)} rows, {path.stat().st_size} bytes, "
      f"encoding reported: {meta.file_encoding}")

# --- multiblock.zsav: zsav whose bytecode stream spans two zlib blocks -----------
# ReadStat writes one block (block size 0x3FF000); the block-descriptor walk in
# the reader is only proven by a file with more than one.

BIAS = 100.0
nvals = [float(i % 200 - 99) for i in range(120)]     # command-byte range
strv = ["blk-%04d" % i for i in range(120)]

# bytecode stream: command bytes + literals, cases of 2 elements (num, str8)
cmd, lits, stream = [], [], b""


def flush():
    global cmd, lits, stream
    if not cmd:
        return
    while len(cmd) < 8:
        cmd.append(0)
    stream += bytes(cmd) + b"".join(lits)
    cmd, lits = [], []


for n, s in zip(nvals, strv):
    for code, lit in ((int(n + BIAS), None), (253, s.ljust(8).encode("ascii"))):
        cmd.append(code)
        if lit is not None:
            lits.append(lit)
        if len(cmd) == 8:
            flush()
cmd.append(252)
flush()

dict_part = header(2, 2, len(nvals), b"multi-block zsav fixture")
dict_part += var_record(0, "N", fmt(5, 8, 2), fmt(5, 8, 2))
dict_part += var_record(8, "S", fmt(1, 8), fmt(1, 8))
dict_part += machine_records(65001)
dict_part += info_record(20, 1, b"UTF-8")
dict_part += struct.pack("<ii", 999, 0)

zheader_ofs = len(dict_part)
half = (len(stream) // 16) * 8
blocks = [stream[:half], stream[half:]]
comp = [zlib.compress(b, 9) for b in blocks]

zheader = struct.pack("<qqq", zheader_ofs, 0, 0)      # trailer ofs/len patched below
descs, u_ofs, c_ofs = b"", zheader_ofs, zheader_ofs + 24
for raw, cz in zip(blocks, comp):
    descs += struct.pack("<qqii", u_ofs, c_ofs, len(raw), len(cz))
    u_ofs += len(raw)
    c_ofs += len(cz)
ztrailer_ofs = c_ofs
ztrailer = struct.pack("<qqii", -int(BIAS), 0, 0x3FF000, len(blocks)) + descs
zheader = struct.pack("<qqq", zheader_ofs, ztrailer_ofs, len(ztrailer))

path = HERE / "multiblock.zsav"
path.write_bytes(dict_part + zheader + b"".join(comp) + ztrailer)
back, meta = pyreadstat.read_sav(str(path))
assert list(back["N"]) == nvals, "numeric mismatch"
assert list(back["S"]) == strv, "string mismatch"
print(f"multiblock.zsav: {len(back)} rows, {path.stat().st_size} bytes, "
      f"{len(blocks)} zlib blocks")
