#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""1:1 Python mirror of ../Crc32.Compute.pq, plus its self-test and fixtures.

M cannot run on this machine, so the table-driven implementation is written
here first, structured exactly like the M, and validated three ways:
  1. against an independent bit-by-bit reference implementation,
  2. against the published check values (CRC of b"123456789") for every variant,
  3. against zlib.crc32 for ISO-HDLC across assorted inputs.
Then it generates sample.bin and expected.md with the values the M port must
reproduce on a real host.

Variant parameters (reflected variants store the reflected polynomial, exactly
as the M does):
"""

import hashlib
import os
import zlib
from pathlib import Path

HERE = Path(__file__).parent

VARIANTS = {
    #            poly        init        reflected  xorout      check("123456789")
    "ISOHDLC": (0xEDB88320, 0xFFFFFFFF, True,  0xFFFFFFFF, 0xCBF43926),
    "CRC32C":  (0x82F63B78, 0xFFFFFFFF, True,  0xFFFFFFFF, 0xE3069283),
    "JAMCRC":  (0xEDB88320, 0xFFFFFFFF, True,  0x00000000, 0x340BC6D9),
    "BZIP2":   (0x04C11DB7, 0xFFFFFFFF, False, 0xFFFFFFFF, 0xFC891918),
    "MPEG2":   (0x04C11DB7, 0xFFFFFFFF, False, 0x00000000, 0x0376E6E7),
}


# --------------------------------------------------------------------------
# mirror of the M implementation: 256-entry table, one pass, 32-bit safe
# --------------------------------------------------------------------------

def make_table(poly: int, reflected: bool):
    table = []
    for n in range(256):
        c = n if reflected else n << 24
        for _ in range(8):
            if reflected:
                c = (c >> 1) ^ poly if c & 1 else c >> 1
            else:
                c = ((c << 1) ^ poly) & 0xFFFFFFFF if c & 0x80000000 else (c << 1) & 0xFFFFFFFF
        table.append(c)
    return table


def crc32_table(data: bytes, variant: str = "ISOHDLC") -> int:
    poly, init, reflected, xorout, _ = VARIANTS[variant]
    table = make_table(poly, reflected)
    crc = init
    if reflected:
        for b in data:
            crc = (crc >> 8) ^ table[(crc ^ b) & 0xFF]
    else:
        for b in data:
            crc = ((crc << 8) & 0xFFFFFFFF) ^ table[(crc >> 24) ^ b]
    return crc ^ xorout


def snappy_mask(crc: int) -> int:
    """Snappy framing-format CRC masking: rotate right 15, add a constant."""
    return (((crc >> 15) | ((crc << 17) & 0xFFFFFFFF)) + 0xA282EAD8) & 0xFFFFFFFF


def snappy_unmask(masked: int) -> int:
    rot = (masked - 0xA282EAD8) & 0xFFFFFFFF
    return ((rot >> 17) | ((rot << 15) & 0xFFFFFFFF)) & 0xFFFFFFFF


# --------------------------------------------------------------------------
# independent reference: bit-by-bit, no table
# --------------------------------------------------------------------------

def crc32_bitwise(data: bytes, variant: str) -> int:
    poly, init, reflected, xorout, _ = VARIANTS[variant]
    crc = init
    if reflected:
        for b in data:
            crc ^= b
            for _ in range(8):
                crc = (crc >> 1) ^ (poly if crc & 1 else 0)
    else:
        for b in data:
            crc ^= b << 24
            for _ in range(8):
                crc = ((crc << 1) ^ (poly if crc & 0x80000000 else 0)) & 0xFFFFFFFF
    return crc ^ xorout


# --------------------------------------------------------------------------
# self-test + fixture generation
# --------------------------------------------------------------------------

def main():
    check_input = b"123456789"
    samples = [b"", b"a", check_input, b"hello world", bytes(range(256)), os.urandom(1000)]

    for variant, (_, _, _, _, check) in VARIANTS.items():
        assert crc32_table(check_input, variant) == check, (variant, "check value")
        for s in samples:
            assert crc32_table(s, variant) == crc32_bitwise(s, variant), (variant, "table vs bitwise")
    for s in samples:
        assert crc32_table(s, "ISOHDLC") == zlib.crc32(s), "zlib cross-check"
        assert crc32_table(s, "JAMCRC") == zlib.crc32(s) ^ 0xFFFFFFFF, "JAMCRC relation"
        assert crc32_table(s, "MPEG2") == crc32_table(s, "BZIP2") ^ 0xFFFFFFFF, "MPEG2 relation"
        m = snappy_mask(crc32_table(s, "CRC32C"))
        assert snappy_unmask(m) == crc32_table(s, "CRC32C"), "snappy mask roundtrip"

    fixture = bytes(range(256)) * 4 + b"crc32 utility fixture\n"
    (HERE / "sample.bin").write_bytes(fixture)

    lines = ["# crc32 expected values\n"]
    lines.append(f"Generated by crc_mirror.py; validated against a bit-by-bit reference, "
                 f"published check values, and zlib. sample.bin: {len(fixture)} bytes, "
                 f"sha256 {hashlib.sha256(fixture).hexdigest()}.\n")
    lines.append("Every value below must be reproduced by Crc32.Compute on a real host, "
                 "e.g. `Number.ToText(Crc32.Compute(File.Contents(\"...\\sample.bin\"), \"CRC32C\"), \"X8\")`.\n")
    lines.append('| Variant | check (b"123456789") | empty input | sample.bin |')
    lines.append("|---|---|---|---|")
    for variant in VARIANTS:
        row = [variant] + [f"{crc32_table(d, variant):08X}" for d in (check_input, b"", fixture)]
        lines.append("| " + " | ".join(row) + " |")
    masked = snappy_mask(crc32_table(fixture, "CRC32C"))
    lines.append(f"\nSnappy-masked CRC-32C of sample.bin "
                 f"(`Crc32.Compute(data, \"CRC32C\", [SnappyMask = true])`): {masked:08X}\n")
    (HERE / "expected.md").write_text("\n".join(lines))

    print(f"all variants pass: check values, bitwise cross-check, zlib, mask roundtrip")
    print(f"fixtures written: sample.bin ({len(fixture)} bytes), expected.md")


if __name__ == "__main__":
    main()
