# SPDX-License-Identifier: Apache-2.0
#
# Regenerates the .avro fixtures in this directory. Deterministic: fixed record
# values and fixed sync markers, so reruns are byte-identical.
#
#   python3 -m venv venv && venv/bin/pip install fastavro
#   venv/bin/python make_fixtures.py
#
# All fixtures are synthetic and generated by this script; no third-party or
# customer data. Keep them small.

import datetime
import decimal
import io
import json
import uuid
from pathlib import Path

import fastavro

HERE = Path(__file__).parent
SYNC = b"powerquery-dless"  # 16 bytes, fixed for reproducibility
UTC = datetime.timezone.utc


def write(name, schema, records, codec="null", sync_interval=16000):
    path = HERE / name
    with open(path, "wb") as fo:
        fastavro.writer(
            fo,
            fastavro.parse_schema(schema),
            records,
            codec=codec,
            sync_interval=sync_interval,
            sync_marker=SYNC,
        )
    # round-trip check with the reference implementation
    with open(path, "rb") as fo:
        back = list(fastavro.reader(fo))
    assert len(back) == len(records), name
    print(f"{name}: {len(back)} rows, {path.stat().st_size} bytes")
    return back


# --- scalars: every primitive type plus the nullable-string idiom ---------------

scalars_schema = {
    "type": "record",
    "name": "Scalars",
    "namespace": "driverless.test",
    "fields": [
        {"name": "b", "type": "boolean"},
        {"name": "i", "type": "int"},
        {"name": "l", "type": "long"},
        {"name": "f", "type": "float"},
        {"name": "d", "type": "double"},
        {"name": "s", "type": "string"},
        {"name": "by", "type": "bytes"},
        {"name": "maybe", "type": ["null", "string"]},
    ],
}

scalars_rows = [
    dict(b=True, i=0, l=0, f=0.0, d=0.0, s="", by=b"", maybe=None),
    dict(b=False, i=-1, l=4503599627370496, f=1.5, d=-2.75,
         s="héllo ✓", by=b"\x00\xff", maybe="present"),
    dict(b=True, i=2147483647, l=-4611686018427387904, f=-0.5, d=1e300,
         s="line\nbreak", by=b"avro", maybe=None),
    dict(b=False, i=-2147483648, l=1, f=100.0, d=-0.0,
         s="tab\there", by=b"\x01", maybe=""),
]

write("scalars.avro", scalars_schema, scalars_rows)
write("scalars-deflate.avro", scalars_schema, scalars_rows, codec="deflate")
write("empty.avro", scalars_schema, [])

# --- complex: containers, enum, fixed, multi-branch union, recursion ------------

complex_schema = {
    "type": "record",
    "name": "Complex",
    "namespace": "driverless.test",
    "fields": [
        {"name": "tags", "type": {"type": "array", "items": "string"}},
        {"name": "nums", "type": {"type": "array", "items": "long"}},
        {"name": "attrs", "type": {"type": "map", "values": "int"}},
        {"name": "color", "type": {"type": "enum", "name": "Color",
                                   "symbols": ["RED", "GREEN", "BLUE"]}},
        {"name": "fp", "type": {"type": "fixed", "name": "Quad", "size": 4}},
        {"name": "choice", "type": ["null", "string", "long"]},
        {"name": "nested", "type": {"type": "record", "name": "Point", "fields": [
            {"name": "x", "type": "double"},
            {"name": "y", "type": "double"},
        ]}},
        {"name": "chain", "type": ["null", {"type": "record", "name": "Node", "fields": [
            {"name": "value", "type": "long"},
            {"name": "next", "type": ["null", "Node"]},
        ]}]},
    ],
}

complex_rows = [
    dict(tags=[], nums=[], attrs={}, color="RED", fp=b"\x00\x01\x02\x03",
         choice=None, nested=dict(x=0.0, y=0.0), chain=None),
    dict(tags=["alpha", "beta"], nums=[-1, 0, 1, 300], attrs={"a": 1, "b": -2},
         color="GREEN", fp=b"ABCD", choice="picked",
         nested=dict(x=1.5, y=-2.5),
         chain=dict(value=1, next=dict(value=2, next=dict(value=3, next=None)))),
    dict(tags=["über"], nums=[9007199254740992], attrs={"only": 42},
         color="BLUE", fp=b"\xff\xfe\xfd\xfc", choice=64,
         nested=dict(x=3.14159, y=2.71828),
         chain=dict(value=-7, next=None)),
]

write("complex.avro", complex_schema, complex_rows)

# --- logical types ---------------------------------------------------------------

logical_schema = {
    "type": "record",
    "name": "Logical",
    "namespace": "driverless.test",
    "fields": [
        {"name": "dec", "type": {"type": "bytes", "logicalType": "decimal",
                                 "precision": 10, "scale": 2}},
        {"name": "day", "type": {"type": "int", "logicalType": "date"}},
        {"name": "tmilli", "type": {"type": "int", "logicalType": "time-millis"}},
        {"name": "tmicro", "type": {"type": "long", "logicalType": "time-micros"}},
        {"name": "tsmilli", "type": {"type": "long", "logicalType": "timestamp-millis"}},
        {"name": "tsmicro", "type": {"type": "long", "logicalType": "timestamp-micros"}},
        {"name": "id", "type": {"type": "string", "logicalType": "uuid"}},
    ],
}

logical_rows = [
    dict(dec=decimal.Decimal("12345.67"),
         day=datetime.date(2026, 7, 15),
         tmilli=datetime.time(13, 45, 30, 500000),
         tmicro=datetime.time(23, 59, 59, 999999),
         tsmilli=datetime.datetime(2026, 7, 15, 13, 45, 30, 500000, tzinfo=UTC),
         tsmicro=datetime.datetime(2026, 7, 15, 13, 45, 30, 123456, tzinfo=UTC),
         id=uuid.UUID("00112233-4455-6677-8899-aabbccddeeff")),
    dict(dec=decimal.Decimal("-0.01"),
         day=datetime.date(1969, 12, 31),
         tmilli=datetime.time(0, 0, 0),
         tmicro=datetime.time(0, 0, 0, 1),
         tsmilli=datetime.datetime(1969, 12, 31, 23, 59, 59, tzinfo=UTC),
         tsmicro=datetime.datetime(1970, 1, 1, 0, 0, 0, tzinfo=UTC),
         id=uuid.UUID("ffffffff-ffff-ffff-ffff-ffffffffffff")),
]

write("logical.avro", logical_schema, logical_rows)

# --- Event Hubs Capture shape ----------------------------------------------------
# Mirrors the schema Event Hubs Capture writes (see Microsoft's "Exploring captured
# Avro files in Azure Event Hubs"). Body carries a JSON payload, except one row that
# does not, to exercise the non-JSON fallback.

eventhubs_schema = {
    "type": "record",
    "name": "EventData",
    "namespace": "Microsoft.ServiceBus.Messaging",
    "fields": [
        {"name": "SequenceNumber", "type": "long"},
        {"name": "Offset", "type": "string"},
        {"name": "EnqueuedTimeUtc", "type": "string"},
        {"name": "SystemProperties", "type": {"type": "map",
            "values": ["long", "double", "string", "bytes"]}},
        {"name": "Properties", "type": {"type": "map",
            "values": ["long", "double", "string", "bytes"]}},
        {"name": "Body", "type": ["null", "bytes"]},
    ],
}

eventhubs_rows = [
    dict(SequenceNumber=101, Offset="4960", EnqueuedTimeUtc="7/15/2026 1:45:30 PM",
         SystemProperties={"x-opt-partition-key": "device-1"},
         Properties={"source": "sensor"},
         Body=json.dumps({"deviceId": "device-1", "temperature": 21.5,
                          "ok": True}).encode()),
    dict(SequenceNumber=102, Offset="5312", EnqueuedTimeUtc="7/15/2026 1:45:31 PM",
         SystemProperties={"x-opt-sequence-number": 102},
         Properties={},
         Body=json.dumps({"deviceId": "device-2", "temperature": -3.25,
                          "ok": False}).encode()),
    dict(SequenceNumber=103, Offset="5664", EnqueuedTimeUtc="7/15/2026 1:45:32 PM",
         SystemProperties={},
         Properties={"note": "not json"},
         Body=b"plain text body"),
    dict(SequenceNumber=104, Offset="6016", EnqueuedTimeUtc="7/15/2026 1:45:33 PM",
         SystemProperties={},
         Properties={},
         Body=None),
]

write("eventhubs.avro", eventhubs_schema, eventhubs_rows)

# --- multiple data blocks ---------------------------------------------------------

multiblock_schema = {
    "type": "record",
    "name": "Row",
    "namespace": "driverless.test",
    "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
    ],
}

multiblock_rows = [dict(id=i, name=f"row-{i:04d}") for i in range(200)]

write("multiblock.avro", multiblock_schema, multiblock_rows, sync_interval=256)

# confirm the multiblock fixture really has more than one data block
with open(HERE / "multiblock.avro", "rb") as fo:
    nblocks = sum(1 for _ in fastavro.block_reader(fo))
assert nblocks > 1, "multiblock.avro ended up with a single block"
print(f"multiblock.avro: {nblocks} data blocks")
