# SPDX-License-Identifier: Apache-2.0
#
# Regenerates the .dta fixtures in this directory.
#
#   python3 -m venv venv && venv/bin/pip install pyreadstat pandas
#   venv/bin/python make_fixtures.py
#
# Most fixtures are written with pandas (its Stata writer preserves all five
# numeric storage types and writes strLs) or pyreadstat (a wrapper over
# ReadStat, the reference reader/writer used by R haven and Python; it writes
# every dta version and extended missing values). Two are hand-crafted byte
# by byte because neither library can write them: a big-endian (MSF) 118
# file, and a legacy codepage-1252 format-114 file with expansion fields.
# Both are read back with a reference reader after writing, so every fixture
# in this directory is confirmed readable by a reference implementation.
#
# All fixtures are synthetic and generated by this script; no third-party or
# customer data. Reruns are byte-identical except for the timestamp the
# writers stamp into the header.

import datetime
import struct
from pathlib import Path

import numpy as np
import pandas as pd
import pyreadstat

HERE = Path(__file__).parent


def release_of(path):
    raw = open(path, "rb").read(40)
    if raw[:10] == b"<stata_dta":
        i = raw.index(b"<release>") + 9
        return int(raw[i:i + 3])
    return raw[0]


def report(name, nrows, ncols):
    path = HERE / name
    print(f"{name}: format {release_of(path)}, {nrows} rows x {ncols} cols, "
          f"{path.stat().st_size} bytes")


# --- types: all five numeric storage types + strf, in four container versions ----
#
# Numeric values sit on the documented valid-range edges: byte -127..100,
# int -32767..32740, long -2147483647..2147483620, float valid max is
# (2 - 2^-23) * 2^126 ~ 1.70e38 (anything >= 2^127 is a missing code),
# double valid max +8.988e307 (anything >= 2^1023 is a missing code).
# The None in vdouble becomes a system missing (.). vstr proves that
# trailing spaces are significant (strfs are \0-terminated, never padded).

types_df = pd.DataFrame({
    "vbyte": np.array([-127, 100, 0], dtype=np.int8),
    "vint": np.array([-32767, 32740, 1], dtype=np.int16),
    "vlong": np.array([-2147483647, 2147483620, 2], dtype=np.int32),
    "vfloat": np.array([-1.5e38, 1.5e38, 0.25], dtype=np.float32),
    "vdouble": [8.988e307, -8.988e307, None],
    "vstr": ["abcdefgh", "sp ", ""],       # 8 = declared width: no terminator
})

for version in (114, 117, 118, 119):
    name = f"types{version}.dta"
    types_df.to_stata(HERE / name, version=version, write_index=False)
    back = pd.read_stata(HERE / name)
    assert list(back["vstr"]) == ["abcdefgh", "sp ", ""], name
    assert back["vdouble"][2] != back["vdouble"][2], name  # NaN = sysmiss
    report(name, len(back), len(back.columns))

# --- types113 / types115: the two legacy containers pandas cannot write ----------
#
# ReadStat promotes small ints to long and float to double, so these two only
# prove the container differences: ds_format bytes 0x71/0x73 and the 12-byte
# (113) versus 49-byte (115) display-format field.

legacy_df = pd.DataFrame({
    "num": [1.5, -2.75, 1e300],
    "count": np.array([1, 2, 3], dtype=np.int32),
    "name": ["alpha", "", "z"],
})
for stata_version, fmt in ((8, 113), (12, 115)):
    name = f"types{fmt}.dta"
    pyreadstat.write_dta(legacy_df, str(HERE / name), version=stata_version)
    back, _ = pyreadstat.read_dta(str(HERE / name))
    assert list(back["name"]) == ["alpha", "", "z"], name
    report(name, len(back), len(back.columns))

# --- labels: the dictionary fixture --------------------------------------------
#
# Value labels, variable labels, a dataset label, and extended missing
# values: pyreadstat represents .a-.z cells as the strings "a".."z" when
# missing_user_values declares them. gender row 4 is .a, rating row 3 is .z,
# rating row 4 is system-missing.

labels_df = pd.DataFrame({
    "gender": [1.0, 2.0, 1.0, "a"],
    "rating": [1.0, 5.0, "z", None],
    "note": ["fine", "bad", "", "ok"],
})
pyreadstat.write_dta(
    labels_df, str(HERE / "labels118.dta"), version=14,
    file_label="driverless label fixture",
    column_labels={"gender": "Respondent gender",
                   "rating": "Satisfaction rating",
                   "note": "Free-text note"},
    variable_value_labels={
        "gender": {1: "Male", 2: "Female"},
        "rating": {1: "Awful", 5: "Great"},
    },
    missing_user_values={"gender": ["a"], "rating": ["z"]},
)
back, meta = pyreadstat.read_dta(str(HERE / "labels118.dta"), user_missing=True)
assert list(back["gender"]) == [1.0, 2.0, 1.0, "a"]
assert meta.variable_value_labels["gender"][1] == "Male"
report("labels118.dta", len(back), len(back.columns))

# --- dates: the 1960-01-01 epoch in every %t flavor ----------------------------
#
# Stored values are plain numbers; only the display format says they are
# dates. %td days, %tc milliseconds, %tm months, %tq quarters, %th
# half-years, %tw weeks (52 per year, week 52 absorbs the leftover days),
# %ty literal year, and the old %d notation (= %td).

D0 = datetime.date(1960, 1, 1)
dates_df = pd.DataFrame({
    "td": [float((datetime.date(2026, 7, 15) - D0).days), 0.0, -1.0, None],
    "tc": [((datetime.datetime(2026, 7, 15, 13, 45, 30) -
             datetime.datetime(1960, 1, 1)).total_seconds() * 1000 + 123),
           0.0, 86399999.0, None],
    "tm": [(2026 - 1960) * 12 + 6.0, 0.0, -1.0, None],
    "tq": [(2026 - 1960) * 4 + 2.0, 0.0, -1.0, None],
    "th": [(2026 - 1960) * 2 + 1.0, 0.0, -1.0, None],
    "tw": [(2026 - 1960) * 52 + 28.0, 0.0, 51.0, None],
    "ty": [2026.0, 1960.0, 1900.0, None],
    "dold": [0.0, 100.0, -100.0, None],
})
pyreadstat.write_dta(
    dates_df, str(HERE / "dates118.dta"), version=14,
    variable_format={"td": "%td", "tc": "%tc", "tm": "%tm", "tq": "%tq",
                     "th": "%th", "tw": "%tw", "ty": "%ty", "dold": "%d"})
back, meta = pyreadstat.read_dta(str(HERE / "dates118.dta"))
assert back["td"][0] == datetime.date(2026, 7, 15), back["td"][0]
report("dates118.dta", len(back), len(back.columns))

# --- strL: long strings behind (v,o) pointers ----------------------------------
#
# strl117 proves the 117 encoding ((v,o) as two 4-byte ints in the data,
# 4-byte o in the GSO); strl118 proves the 118 one (2+6 bytes in the data,
# 8-byte o in the GSO). Values: a 3000-byte string (longer than any strf),
# an empty string ((v,o) = (0,0), no GSO), a short string, and a repeat of
# the long one. n trails the strL to prove row alignment past the pointer.

strl_values = ["long" * 750, "", "short one", "long" * 750]
for version in (117, 118):
    # 117 predates Unicode: pandas encodes its strings latin-1
    accent = "héllo ✓" if version == 118 else "héllo"
    strl_df = pd.DataFrame({
        "sl": strl_values,
        "n": [1.0, 2.0, 3.0, 4.0],
        "su": [accent, "", "plain", "a"],
    })
    name = f"strl{version}.dta"
    strl_df.to_stata(HERE / name, version=version,
                     convert_strl=["sl"], write_index=False)
    back = pd.read_stata(HERE / name)
    assert list(back["sl"]) == strl_values, name
    assert list(back["su"]) == list(strl_df["su"]), name
    report(name, len(back), len(back.columns))

# --- empty: dictionary but zero observations -----------------------------------

empty_df = pd.DataFrame({"a": pd.Series(dtype="float64"),
                         "b": pd.Series(dtype="str")})
empty_df.to_stata(HERE / "empty118.dta", version=118, write_index=False)
back = pd.read_stata(HERE / "empty118.dta")
assert len(back) == 0 and list(back.columns) == ["a", "b"]
report("empty118.dta", 0, 2)


# =================================================================================
# Hand-crafted fixtures. pandas and ReadStat write little-endian (LSF) only,
# never write characteristics or a sort order, and cannot put a value label
# on an extended missing code. Both files are verified by reading them back
# with pandas, which does read MSF files.
# =================================================================================

def vallab_table(labname, mapping, name_len, endian):
    # mapping: value (int) -> text. val[] must be ascending.
    items = sorted(mapping.items())
    txt = b""
    offs = []
    for _, text in items:
        offs.append(len(txt))
        txt += text + b"\0"
    table = struct.pack(f"{endian}ii", len(items), len(txt))
    table += b"".join(struct.pack(f"{endian}i", o) for o in offs)
    table += b"".join(struct.pack(f"{endian}i", v) for v, _ in items)
    table += txt
    return (struct.pack(f"{endian}i", len(table))
            + labname.ljust(name_len, b"\0") + b"\0\0\0" + table)


# --- legacy1252.dta: format 114, LSF, codepage-1252, expansion fields ----------
#
# The shape of a pre-Unicode Stata file (Stata 10, saved on Windows):
# accented cp1252 strings and labels, a real sort order, and two expansion
# fields the reader must skip (5-byte header: type byte + 4-byte length).

E = "<"
enc = lambda s: s.encode("cp1252")

hdr = struct.pack(f"{E}BBBBhi", 114, 2, 1, 0, 3, 4)          # LSF, 3 vars, 4 obs
hdr += enc("légacy fixture").ljust(81, b"\0")
hdr += b"18 Jul 2026 12:00\0"
typlist = bytes([255, 12, 251])                              # double, str12, byte
varlist = b"".join(n.ljust(33, b"\0") for n in [b"num", b"city", b"grp"])
srtlist = struct.pack(f"{E}4h", 3, 0, 0, 0)                  # sorted by grp
fmtlist = b"".join(f.ljust(49, b"\0") for f in [b"%9.2f", b"%12s", b"%8.0g"])
lbllist = b"".join(n.ljust(33, b"\0") for n in [b"", b"", b"grplbl"])
varlabels = (enc("Numéro").ljust(81, b"\0")
             + enc("Ville").ljust(81, b"\0") + b"\0" * 81)
ch1 = b"grp".ljust(33, b"\0") + b"note".ljust(33, b"\0") + b"gone\0"
ch2 = b"num".ljust(33, b"\0") + b"unit".ljust(33, b"\0") + b"m\0"
expansion = (b"\x01" + struct.pack(f"{E}i", len(ch1)) + ch1
             + b"\x01" + struct.pack(f"{E}i", len(ch2)) + ch2
             + b"\x00" + struct.pack(f"{E}i", 0))

rows = [(1.25, "Málaga", 1), (-0.5, "Zürich", 1),
        (float("nan"), "", 2), (3.0, "León", 102)]      # nan -> ., 102 -> .a
data = b""
for num, city, grp in rows:
    numbits = 0x7FE0000000000000 if num != num else struct.unpack("<Q", struct.pack("<d", num))[0]
    data += struct.pack(f"{E}Q", numbits)
    c = enc(city)
    data += c if len(c) == 12 else c + b"\0" * (12 - len(c))
    data += struct.pack(f"{E}b", grp)
vallabs = vallab_table(b"grplbl", {1: enc("prémier"), 2: enc("deuxième")},
                       33, E)

path = HERE / "legacy1252.dta"
path.write_bytes(hdr + typlist + varlist + srtlist + fmtlist + lbllist
                 + varlabels + expansion + data + vallabs)
back = pd.read_stata(str(path))
assert list(back["city"]) == ["Málaga", "Zürich", "", "León"], \
    list(back["city"])
assert list(back["grp"])[:2] == ["prémier", "prémier"]
report("legacy1252.dta", len(back), len(back.columns))

# --- msf118.dta: format 118, big-endian (MSF), characteristics, strL, ----------
# --- and a value label on an extended missing code -----------------------------
#
# Old Solaris/AIX Stata wrote MSF; modern readers must byte-swap. The one
# characteristic's contents contain the literal string "</characteristics>"
# to punish readers that scan for the close tag instead of walking <ch>
# lengths. id row 3 is .a (long code 0x7FFFFFE6), which carries a value
# label; id row 4 is . (0x7FFFFFE5). The strL column has a GSO-backed value,
# a cross-link to it, an empty (0,0), and a binary (t=129) GSO.

E = ">"

def tag(name, body=b""):
    return b"<" + name + b">" + body + b"</" + name + b">"

K, N = 3, 4
header = tag(b"header",
             tag(b"release", b"118") + tag(b"byteorder", b"MSF")
             + tag(b"K", struct.pack(f"{E}H", K))
             + tag(b"N", struct.pack(f"{E}Q", N))
             + tag(b"label", struct.pack(f"{E}H", 11) + b"MSF fixture")
             + tag(b"timestamp", b"\x1118 Jul 2026 12:00"))

types = tag(b"variable_types", struct.pack(f"{E}3H", 65528, 6, 32768))
varnames = tag(b"varnames",
               b"".join(n.ljust(129, b"\0") for n in [b"id", b"name", b"blob"]))
srt = tag(b"sortlist", struct.pack(f"{E}4H", 1, 0, 0, 0))
fmts = tag(b"formats",
           b"".join(f.ljust(57, b"\0") for f in [b"%12.0g", b"%9s", b"%9s"]))
lblnames = tag(b"value_label_names",
               b"".join(n.ljust(129, b"\0") for n in [b"idlbl", b"", b""]))
varlabels = tag(b"variable_labels",
                b"Identifier".ljust(321, b"\0") + b"\0" * 321 + b"\0" * 321)
chs = tag(b"characteristics",
          tag(b"ch", struct.pack(f"{E}I", 258 + 30)
              + b"id".ljust(129, b"\0") + b"trap".ljust(129, b"\0")
              + b"has </characteristics> inside\0"))

MISS_A = 0x7FFFFFE6                       # .a for long
MISS_DOT = 0x7FFFFFE5                     # .  for long

def vo(v, o):                             # 118 MSF: 2-byte v, 6-byte o
    return struct.pack(f"{E}H", v) + struct.pack(f"{E}Q", o)[2:]

datarows = [
    (1, b"first\0", vo(3, 1)),            # GSO-backed "hello strL"
    (2, b"second", vo(3, 1)),             # cross-link to (3,1)
    (MISS_A, b"\0" * 6, vo(0, 0)),        # empty strL, .a id
    (MISS_DOT, b"x\0abc\0", vo(3, 4)),    # binary GSO
]
data = tag(b"data", b"".join(struct.pack(f"{E}i", i) + s + p
                             for i, s, p in datarows))
gso = (b"GSO" + struct.pack(f"{E}IQ", 3, 1) + b"\x82"
       + struct.pack(f"{E}I", 11) + b"hello strL\0"
       + b"GSO" + struct.pack(f"{E}IQ", 3, 4) + b"\x81"
       + struct.pack(f"{E}I", 4) + b"P\0NG")
strls = tag(b"strls", gso)
vallabs = tag(b"value_labels",
              tag(b"lbl", vallab_table(b"idlbl",
                                       {1: b"one", 2: b"two",
                                        MISS_A: b"refused"}, 129, E)))

sections = [header, b"", types, varnames, srt, fmts, lblnames, varlabels,
            chs, data, strls, vallabs]
# assemble with the map: 14 offsets, entry 2 is the map itself
prefix = b"<stata_dta>"
maplen = len(tag(b"map", b"\0" * 112))
offsets, pos = [], len(prefix)
for i, s in enumerate(sections):
    if i == 1:
        offsets.append(pos)               # <map>
        pos += maplen
    else:
        offsets.append(pos)
        pos += len(s)
offsets[0] = 0                            # <stata_dta>
offsets.append(pos)                       # </stata_dta>
offsets.append(pos + len(b"</stata_dta>"))  # end of file
themap = tag(b"map", b"".join(struct.pack(f"{E}Q", o) for o in offsets))
assert len(themap) == maplen
body = prefix + sections[0] + themap + b"".join(sections[2:]) + b"</stata_dta>"

path = HERE / "msf118.dta"
path.write_bytes(body)
back = pd.read_stata(str(path))
assert list(back["name"]) == ["first", "second", "", "x"], list(back["name"])
assert list(back["blob"])[:3] == ["hello strL", "hello strL", ""], \
    list(back["blob"])
# pandas 3.x renders the binary (t=129) GSO as either bytes or its repr
assert back["blob"][3] in (b"P\0NG", str(b"P\0NG")), back["blob"][3]
assert back["id"][0] == "one" and back["id"][1] == "two"
report("msf118.dta", len(back), len(back.columns))

print("all fixtures written and verified against a reference reader")
