// SPDX-License-Identifier: Apache-2.0
//
// Regenerates the .mdb / .accdb fixtures in this directory using Jackcess
// (Apache-2.0). All fixtures are synthetic and generated by this file; no
// third-party or customer data. Not byte-deterministic across reruns (the
// format embeds creation timestamps), but the logical content is fixed and
// documented in expected.md.
//
//   curl -sSLO https://repo1.maven.org/maven2/com/healthmarketscience/jackcess/jackcess/4.0.7/jackcess-4.0.7.jar
//   curl -sSLO https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
//   curl -sSLO https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
//   java -cp "jackcess-4.0.7.jar:commons-lang3-3.12.0.jar:commons-logging-1.2.jar:." MakeFixtures.java
//
// encrypted.mdb is NOT produced here; it is synthesized by make_encrypted.py
// (a copy of jet4.mdb with a non-zero database key and scrambled pages) to
// exercise the clear-error path for encrypted files.

import com.healthmarketscience.jackcess.ColumnBuilder;
import com.healthmarketscience.jackcess.Cursor;
import com.healthmarketscience.jackcess.CursorBuilder;
import com.healthmarketscience.jackcess.Database;
import com.healthmarketscience.jackcess.DatabaseBuilder;
import com.healthmarketscience.jackcess.DataType;
import com.healthmarketscience.jackcess.Table;
import com.healthmarketscience.jackcess.TableBuilder;

import java.io.File;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collections;

public class MakeFixtures {

    public static void main(String[] args) throws Exception {
        File here = new File(args.length > 0 ? args[0] : ".");
        makeDb(new File(here, "jet4.mdb"), Database.FileFormat.V2000, true);
        makeDb(new File(here, "ace.accdb"), Database.FileFormat.V2016, false);
        System.out.println("done");
    }

    static void makeDb(File file, Database.FileFormat fmt, boolean isJet4) throws Exception {
        if (file.exists() && !file.delete()) throw new IllegalStateException("cannot delete " + file);
        boolean withBigInt = !isJet4;

        try (Database db = new DatabaseBuilder(file).setFileFormat(fmt).create()) {

            // ---- Types: one column per supported data type, edge-case rows ----
            TableBuilder tb = new TableBuilder("Types")
                .addColumn(new ColumnBuilder("Id", DataType.LONG))
                .addColumn(new ColumnBuilder("TByte", DataType.BYTE))
                .addColumn(new ColumnBuilder("TInt", DataType.INT))
                .addColumn(new ColumnBuilder("TLong", DataType.LONG))
                .addColumn(new ColumnBuilder("TCurrency", DataType.MONEY))
                .addColumn(new ColumnBuilder("TFloat", DataType.FLOAT))
                .addColumn(new ColumnBuilder("TDouble", DataType.DOUBLE))
                .addColumn(new ColumnBuilder("TDate", DataType.SHORT_DATE_TIME))
                .addColumn(new ColumnBuilder("TText", DataType.TEXT).setLengthInUnits(100))
                .addColumn(new ColumnBuilder("TMemo", DataType.MEMO))
                .addColumn(new ColumnBuilder("TBool", DataType.BOOLEAN))
                .addColumn(new ColumnBuilder("TGuid", DataType.GUID))
                .addColumn(new ColumnBuilder("TNumeric", DataType.NUMERIC).setPrecision(18).setScale(4))
                .addColumn(new ColumnBuilder("TBinary", DataType.BINARY).setLengthInUnits(255))
                .addColumn(new ColumnBuilder("TOle", DataType.OLE));
            if (withBigInt) tb.addColumn(new ColumnBuilder("TBigInt", DataType.BIG_INT));
            Table types = tb.toTable(db);

            byte[] bin1 = {1, 2, 3, 4};
            byte[] bin300 = new byte[200];
            for (int i = 0; i < bin300.length; i++) bin300[i] = (byte) (i & 0xFF);
            byte[] ole10k = new byte[10000];
            for (int i = 0; i < ole10k.length; i++) ole10k[i] = (byte) ((i * 7) & 0xFF);
            String memo20k = "0123456789".repeat(2000);

            addRow(types, withBigInt, new Object[]{
                1, (byte) 7, (short) -12345, 123456789, new BigDecimal("1234.5678"),
                1.5f, 2.75, LocalDateTime.of(2026, 7, 15, 13, 45, 30),
                "hello", "short memo", true,
                "{00112233-4455-6677-8899-AABBCCDDEEFF}",
                new BigDecimal("1234.5678"), bin1, ole10k}, 42L);
            addRow(types, withBigInt, new Object[]{
                2, null, null, null, null, null, null, null,
                null, null, false, null, null, null, null}, null);
            addRow(types, withBigInt, new Object[]{
                3, (byte) 255, (short) 32767, -2147483648, new BigDecimal("-0.0001"),
                -3.25f, -1.0E10, LocalDateTime.of(1899, 12, 25, 6, 0, 0),
                "Ünïcødé テスト", memo20k, true,
                "{FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF}",
                new BigDecimal("-9999.9999"), bin300, null}, 4503599627370496L);
            addRow(types, withBigInt, new Object[]{
                4, (byte) 0, (short) 0, 0, BigDecimal.ZERO,
                0.0f, 0.0, LocalDateTime.of(1899, 12, 30, 0, 0, 0),
                "", "", false, null, new BigDecimal("0.0001"),
                new byte[0], null}, -1L);

            // ---- Empty: columns but no rows ----
            new TableBuilder("Empty")
                .addColumn(new ColumnBuilder("Id", DataType.LONG))
                .addColumn(new ColumnBuilder("Note", DataType.TEXT).setLengthInUnits(50))
                .toTable(db);

            // ---- Many: enough rows for multiple data pages; one delete, one
            //      in-place growth (overflow candidate) ----
            int n = isJet4 ? 3000 : 1000;
            Table many = new TableBuilder("Many")
                .addColumn(new ColumnBuilder("Id", DataType.LONG))
                .addColumn(new ColumnBuilder("Val", DataType.TEXT).setLengthInUnits(255))
                .toTable(db);
            for (int i = 1; i <= n; i++) many.addRow(i, String.format("row-%04d", i));
            Cursor cur = CursorBuilder.createCursor(many);
            if (cur.findFirstRow(Collections.singletonMap("Id", 77))) cur.deleteCurrentRow();
            if (cur.findFirstRow(Collections.singletonMap("Id", 42)))
                cur.setCurrentRowValue(many.getColumn("Val"), "grown ".repeat(40).trim());

            // ---- Unicode: compressed / uncompressed / mixed text ----
            Table uni = new TableBuilder("Unicode")
                .addColumn(new ColumnBuilder("Id", DataType.LONG))
                .addColumn(new ColumnBuilder("Txt", DataType.TEXT).setLengthInUnits(255))
                .toTable(db);
            uni.addRow(1, "plain ascii");
            uni.addRow(2, "日本語テキスト");           // all 2-byte
            uni.addRow(3, "mix: ascii + Ωμέγα + 中文"); // toggles
            uni.addRow(4, "");
            uni.addRow(5, (Object) null);

            // ---- Wide: 150 columns -> multi-page table definition ----
            TableBuilder wb = new TableBuilder("Wide");
            for (int i = 1; i <= 150; i++)
                wb.addColumn(new ColumnBuilder(String.format("C%03d", i), DataType.TEXT).setLengthInUnits(20));
            Table wide = wb.toTable(db);
            Object[] row = new Object[150];
            for (int i = 0; i < 150; i++) row[i] = String.format("v%03d", i + 1);
            wide.addRow(row);
            wide.addRow(new Object[150]); // all nulls
        }
        System.out.println("wrote " + file + " (" + file.length() + " bytes)");
    }

    static void addRow(Table t, boolean withBigInt, Object[] vals, Long bigInt) throws Exception {
        if (!withBigInt) { t.addRow(vals); return; }
        Object[] all = new Object[vals.length + 1];
        System.arraycopy(vals, 0, all, 0, vals.length);
        all[vals.length] = bigInt;
        t.addRow(all);
    }
}
